# Generated by Django 4.0.4 on 2022-11-29 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=20)),
                ('starting_year_class', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=20)),
                ('module_credit', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('form_four_index', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NTA_Level',
            fields=[
                ('level_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=20)),
                ('number_of_semesters', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registration_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('form_four_index', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.course', verbose_name='course_id')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.department', verbose_name='departiment_id')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_Student_result',
            fields=[
                ('result_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('academic_year', models.DateField()),
                ('CA', models.FloatField()),
                ('FE', models.FloatField()),
                ('status', models.CharField(max_length=15)),
                ('module_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.student', verbose_name='registration_number')),
            ],
        ),
        migrations.CreateModel(
            name='Overall_result',
            fields=[
                ('result_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('academic_year', models.DateField()),
                ('GPA', models.FloatField()),
                ('pass_status', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.student', verbose_name='registration_number')),
            ],
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('hod_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hod_name', models.CharField(max_length=20)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.department', verbose_name='department_name')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_year', models.DateField()),
                ('enrollment_status', models.CharField(max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.student', verbose_name='registration_number')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.department', verbose_name='departiment_id'),
        ),
        migrations.CreateModel(
            name='Class_Module',
            fields=[
                ('class_module_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.class', verbose_name='class_id')),
                ('module_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.module', verbose_name='module_code')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='NTA_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.nta_level', verbose_name='NTA_level_id'),
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.course', verbose_name='course_id'),
        ),
    ]
