# Generated by Django 4.0.4 on 2022-11-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0002_remove_hod_hod_name_remove_student_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='form_four_index',
        ),
        migrations.RemoveField(
            model_name='module',
            name='last_name',
        ),
    ]
