# Generated by Django 4.0.4 on 2022-11-29 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0007_remove_enrollment_student_enrollment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='transcript_app.category'),
            preserve_default=False,
        ),
    ]
