# Generated by Django 4.0.4 on 2022-11-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0008_student_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ORDINARY DIPLOMA', 'OD'), ('BACHELOR DEGREE', 'BCH'), ('MASTERS', 'MS')], max_length=20),
        ),
    ]
