# Generated by Django 4.0.4 on 2022-12-01 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0019_alter_semester_student_result_nta_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='nta_level',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transcript_app.category'),
        ),
    ]
