# Generated by Django 4.0.4 on 2022-12-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0020_nta_level_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nta_level',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.category'),
        ),
    ]
