# Generated by Django 4.0.4 on 2023-02-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0029_remove_student_form_four_index_remove_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
    ]
