# Generated by Django 4.0.4 on 2023-02-11 05:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0031_alter_overallresult_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTALevel',
            fields=[
                ('level_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[(4, 'asic Technician Certificate'), (5, 'Technician Certificate'), (6, 'Ordinary Diploma'), (7, 'Higher National Diploma'), (8, 'Bachelor Degree'), (9, 'Masters')], max_length=20)),
                ('number_of_semesters', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(2)])),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='nta_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.ntalevel', verbose_name='NTA_level'),
        ),
        migrations.AlterField(
            model_name='overallresult',
            name='nta_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.ntalevel'),
        ),
        migrations.AlterField(
            model_name='student_semester_result',
            name='nta_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.ntalevel', verbose_name='NTA Level'),
        ),
        migrations.DeleteModel(
            name='NTA_Level',
        ),
    ]
