# Generated by Django 4.0.4 on 2023-02-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0032_ntalevel_alter_class_nta_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='starting_year_class',
            new_name='starting_year',
        ),
        migrations.AlterField(
            model_name='class',
            name='nta_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.ntalevel', verbose_name='level'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.department', verbose_name='departiment')),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.program', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.program', verbose_name='course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
