# Generated by Django 4.0.4 on 2023-02-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0033_rename_starting_year_class_class_starting_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='course',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='program',
        ),
    ]
