# Generated by Django 4.0.4 on 2023-02-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0035_alter_class_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntalevel',
            name='level',
            field=models.CharField(choices=[(4, 'Basic Technician Certificate'), (5, 'Technician Certificate'), (6, 'Ordinary Diploma'), (7, 'Higher National Diploma'), (8, 'Bachelor Degree'), (9, 'Masters')], max_length=20),
        ),
    ]
