# Generated by Django 4.0.4 on 2023-02-11 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transcript_app', '0037_alter_ntalevel_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='transcript_app.hod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hod',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
