# Generated by Django 4.0.4 on 2023-02-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0038_remove_hod_department_department_hod_alter_hod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript_app.program'),
        ),
    ]
