# Generated by Django 4.0.4 on 2023-02-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0039_alter_student_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='nta_level',
        ),
    ]
