# Generated by Django 4.0.4 on 2023-02-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0042_remove_class_module_id_class_module_class_module_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
