# Generated by Django 4.0.4 on 2023-02-23 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0047_rename_department_module_departiment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(default='BENG-20-COE', on_delete=django.db.models.deletion.CASCADE,
                                    to='transcript_app.class', verbose_name='class'),
            preserve_default=False,
        ),
    ]
