# Generated by Django 4.0.4 on 2023-02-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_app', '0048_remove_student_program_student_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='modules',
            field=models.ManyToManyField(to='transcript_app.module'),
        ),
        migrations.DeleteModel(
            name='Class_Module',
        ),
    ]
